config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"

  resources  :articles do
    resources :comments, only:[:create, :destroy], shallow: true
  end
  
  # get '/articles', to: 'articles#index'

  # get '/articles/new', to: 'articles#new'

  # get '/articles/:id', to: 'articles#show', as: 'article'

  # get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  
  # post '/articles', to: 'articles#create'

  # patch '/articles/:id', to: 'articles#update'

  # delete '/articles/:id', to: 'articles#destroy'

  resource :users, except:[:destroy, :show] do
    collection do
      get :login
      post :logining
      delete :logout
    end 
  end

  namespace :api do
    namespace :v1 do
      resources :articles, only:[] do
        member do
          patch :like
        end
      end
    end
  end

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    belongs_to :user
    has_many :comments

    has_many :like_logs
    has_many :users, through: :like_logs
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
    validates :content, presence: true
end

app/models/like_log.rb
class LikeLog < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    #callback method
    before_create :encrypt_password
    
    #validatation
    validates :password, confirmation: true

    validates :email, presence: true, 
               uniqueness: true, 
               format: { 
               with: URI::MailTo::EMAIL_REGEXP, 
               message: '格式有誤' 
               }

    #relationships
    has_many :articles
    has_many :comments

    has_many :like_logs
    has_many :liked_articles, through: :like_logs, source: :article

    # instance methods
    def toggle_like(record)
        if liked?(record)
            unlike!(record) 
            return false
        else
            like!(record)
            return true
        end
    end

    def liked?(record)
        liked_articles.include?(record)
    end

    #class method
    def encrypt_password
        pw = "x#{self.password}y".reverse
        self.password = Digest::SHA1.hexdigest(pw)
    end

    def self.login( email, password )
        return nil if email.empty? or password.empty?

        password = Digest::SHA1.hexdigest("x#{password}y".reverse)

        find_by(email: email, password: password)
    end

    def display_name
        user_name.presence || email.split("@").first.capitalize
    end

    private
    
    def like!(record)
        liked_articles << record
    end
    
    def unlike!(record)
        liked_articles.destroy(record)
    end
    # before_create do encrypt_password(self.password) end

    # def encrypt_password(password)
    #     pw = "x#{password}y".reverse
    #     password = Digest::SHA1.hexdigest(pw)
    # end

    # def self.login( email, password )
    #     return nil if email.empty? or password.empty?

    #     password = Digest::SHA1.hexdigest("x#{password}y".reverse)
    #     password = encrypt_password(password)

    #     find_by(email: email, password: password)
    # end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
    before_action :authenticate_user!
   
    def like
        article = Article.find(params[:id])
    
        status = current_user.toggle_like(article)
        render json: { liked: status }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
    
    def not_found
        render file: Rails.root.join("public", "404.html"),
               status: 404,
               layout: false
    end


    helper_method :user_signed_in?, :current_user

    private

    def user_signed_in?
        session[:member].present?
    end

    def current_user
        if user_signed_in?
            #記憶的方法
            @__user__ = @__user__ || User.find_by(id: session[:member])
        else
            nil
        end
    end
    
    def authenticate_user!
        if not user_signed_in?
          redirect_to login_users_path, notice: '請先登入會員'
        end
      end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [ :show ]
    before_action :authenticate_user!, except: [ :index, :show ]
    before_action :set_user_article, only: [ :edit, :update, :destroy ]
    # before_action :set_article, except: [ :index, :new, :create ]


    def index
        @articles = Article.order(id: :desc)
    end
  
    def show
        @comment = Comment.new
        @comments = @article.comments.order(id: :desc)
    end

    def new
        # @實體變數
        @article = Article.new
    end

    def create
        # @article = Article.new(article_params) 
        @article = current_user.articles.new(article_params) 

        if @article.save
            redirect_to "/articles", notice:"文章新增成功囉 ! "
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            redirect_to articles_path, notice:"文章更新成功囉 ! "
        else
            render :edit
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path, notice:"文章刪除成功囉 ! "
    end

    private
    def article_params
        params.require(:article).permit(:title, :context, :sub_title)
                                # .merge(user: current_user)
    end

    def set_article
        @article = Article.find(params[:id])
    end

    def set_user_article
        @article = current_user.articles.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_article, only: [:create]
    
    def create
        # @comment = Comment.new(params_comment)
        # @comment.user = current_user
        # @comment.article = @article

        @comment = @article.comments.new(params_comment)

        if @comment.save
            redirect_to article_path(@article), notice: '留言成功'
        else
            render "articles/show"    
        end
    end

    def find_article
        @article = Article.find(params[:article_id])
    end
    
    def params_comment
        params.require(:comment).permit(:content).merge(user:current_user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to root_path, notice:"會員新增成功囉 ! "
        else
            render :new
        end
    end

    def login
    end
    
    def logining
        user = User.login(params[:user][:email], params[:user][:password])
        
        session[:member] = user.id

        if user
            redirect_to root_path, notice: '登入成功'
        else
            redirect_to login_users_path, alert: '登入失敗'
        end
    end
    
    def logout
        session[:member] = nil
        redirect_to root_path, notice:"登出成功囉 ! "
    end
    

    def user_params
        params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
    end
    
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, data: { turbo: false }) do |f| %>
  <div>
    <%= f.label :title, '標題' %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :sub_title, '子標題' %>
    <%= f.text_field :sub_title %>
  </div>

  <div>
    <%= f.label :content, '內文' %>
    <%= f.text_area :content %>
  </div>

  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>修改文章</h1>

<%= render 'form', article: @article %>

<!-- <form action="/articles" method="post" data-turbo="false">
    <div>
        <label for="">標題</label>
        <input type="text" name="cc[title]">
    </div>
    <div>
        <label for="">內文</label>
        <textarea name="cc[content]"></textarea>
    </div>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button>GO</button>
</form> -->

app/views/articles/index.html.erb

    <h1>文章列表</h1>

    <%= link_to '新增文章', new_article_path %>

    <ul>
        <% @articles.each do |article| %>
            <li>
                <%= link_to article.title, article_path(article.id) %>
                <%= link_to '更新', edit_article_path(article.id) %>
                <%= link_to '刪除', article_path(article.id), data: { turbo_method: 'delete', turbo_confirm: '確認刪除?' } %>
            </li>
        <% end %>
    </ul>

app/views/articles/new.html.erb
<h1>新增文章</h1>

<%= render 'form', article: @article %>

<!-- <form action="/articles" method="post" data-turbo="false">
    <div>
        <label for="">標題</label>
        <input type="text" name="cc[title]">
    </div>
    <div>
        <label for="">內文</label>
        <textarea name="cc[content]"></textarea>
    </div>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button>GO</button>
</form> -->

app/views/articles/show.html.erb
<h1>
    <%= @article.title %>
    <div data-controller="like" data-id="<%= @article.id %>" data-liked="<%= current_user.liked?(@article) %>">
        <input type="button" value="讚" data-action="click->like#toggle" data-like-target="likebtn">
    </div>
</h1>
<article>
    <p><%= @article.context %></p>
</article>

<hr>

<h2>留言</h2>
<%= form_with( model:@comment ,url: article_comments_path(@article), data: { turbo: false } ) do |f| %>
    <div>
        <%= f.label :content, "留言" %><br>
        <%= f.text_area :content %>
    </div>
    <%= f.submit "新增留言" %>
<% end %>

<ul>
    <% @comments.each do |comment| %>
        <li>
            <%= comment.content %>(<%= comment.created_at %>)
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xretch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "share/navbar" %>
    <%= render "share/flash" %>
    <%= yield %>
    
  </body>
</html>

app/views/share/_flash.html.erb
    <%= flash[:notice] %>
    <%= flash[:alert] %>

app/views/share/_navbar.html.erb
    <nav>
      <ul class="nav">

      <% if user_signed_in? %>
        <li>
          <%= current_user.display_name %>
        </li>
        <li>
          <%= link_to '首頁', root_path %>
        </li>
        <li>
          <%= link_to '登出', logout_users_path, data: {turbo_method: "delete"} %>
        </li>
      <% else %>
        <li>
          <%= link_to '首頁', root_path %>
        </li>
        <li>
          <%= link_to '登入', login_users_path %>
        </li>
        <li>
          <%= link_to '註冊', new_users_path %>
        </li>
      <% end %>
      </ul>
    </nav>

app/views/users/login.html.erb
<h1>會員登入</h1>

<%= form_with( scope: :user, url: logining_users_path , data: { turbo: false } ) do |f| %>

<div>
<%= f.label :email, "信箱" %>
<%= f.email_field :email %>
</div>
<div>
<%= f.label :password, "密碼" %>
<%= f.password_field :password %>
</div>
<%= f.submit "登入" %>

<% end %>

app/views/users/new.html.erb
<h1>註冊帳號</h1>

<%= form_with( model:@user , data: { turbo: false } ) do |f| %>

<div>
<%= f.label :user_name, "使用者名稱" %>
<%= f.text_field :user_name %>
</div>
<div>
<%= f.label :email, "信箱" %>
<%= f.email_field :email %>
</div>
<div>
<%= f.label :password, "密碼" %>
<%= f.password_field :password %>
</div>

<div>
<%= f.label :password_confirmation, "密碼確認" %>
<%= f.password_field :password_confirmation %>
</div>

<%= f.submit "註冊帳號" %>
<% end %>